# Generated by Django 2.0 on 2020-10-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('manufacturer_name', models.CharField(max_length=200, null=True)),
                ('inventory_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date_of_purchase', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('Preference', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
